# Generated by Django 4.0.2 on 2022-02-13 17:13

import accounts.validators
import django.contrib.auth.validators
import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=django.contrib.postgres.fields.citext.CICharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 32 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=32, null=True, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator(), accounts.validators.TelegramUsernameValidator()], verbose_name='username'),
        ),
    ]
